export const ActionTypes = {
  SHOW_OR_HIDE_MENU: "SHOW_OR_HIDE_MENU",
  SHOW_OR_HIDE_ADD_EXERCISE_TO_LIBRARY: "SHOW_OR_HIDE_ADD_EXERCISE_TO_LIBRARY",
  SHOW_OR_HIDE_EXERCISES_LIBRARY: "SHOW_OR_HIDE_EXERCISES_LIBRARY",
};

export default ActionTypes;
