export const ActionTypes = {
  SHOW_OR_HIDE_MENU: "SHOW_OR_HIDE_MENU",
  SHOW_OR_HIDE_ADD_EXERCISE_TO_LIBRARY: "SHOW_OR_HIDE_ADD_EXERCISE_TO_LIBRARY",
  SHOW_OR_HIDE_EXERCISES_LIBRARY: "SHOW_OR_HIDE_EXERCISES_LIBRARY",
  SHOW_OR_HIDE_CHEST: " SHOW_OR_HIDE_CHEST",
  SHOW_OR_HIDE_BACK: " SHOW_OR_HIDE_BACK",
  SHOW_OR_HIDE_LEGS: " SHOW_OR_HIDE_LEGS",
  SHOW_OR_HIDE_SHOULDERS: " SHOW_OR_HIDE_SHOULDERS",
  SHOW_OR_HIDE_BICEPS: " SHOW_OR_HIDE_BICEPS",
  SHOW_OR_HIDE_TRICEPS: " SHOW_OR_HIDE_TRICEPS",
  SHOW_OR_HIDE_ADBOMEN: " SHOW_OR_HIDE_ADBOMEN",
  SHOW_OR_HIDE_OTHER: " SHOW_OR_HIDE_OTHER",
  SHOW_OR_HIDE_BODY_PART: "SHOW_OR_HIDE_BODY_PART",
  ADD_TO_EXERCISE_INPUT: "ADD_TO_EXERCISE_INPUT",

  EXERCISE_INPUT_CHANGE: "EXERCISE_INPUT_CHANGE",
};

export default ActionTypes;
