export const ActionTypes = {
  SHOW_OR_HIDE_STOPWATCH: "SHOW_OR_HIDE_STOPWATCH",
  SERIES_SECONDS_CHANGE: "SERIES_SECONDS_CHANGE",
  WORKOUT_SECONDS_CHANGE: "WORKOUT_SECONDS_CHANGE",
  REST_SECONDS_CHANGE: "REST_SECONDS_CHANGE",

  SERIES_MINUTES_CHANGE: "SERIES_MINUTES_CHANGE",
  WORKOUT_MINUTES_CHANGE: "WORKOUT_MINUTES_CHANGE",
  REST_MINUTES_CHANGE: "REST_MINUTES_CHANGE",
};
