export const ActionTypes = {
  SET_EXERCISE_ACTION: "SET_EXERCISE_ACTION",
  FINISH_EXERCISE_ACTION: "FINISH_EXERCISE_ACTION",
  SET_TRAINING_ACTION: "SET_TRAINING_ACTION",
  NUMBER_CHANGE: "NUMBER_CHANGE",
};
